### ISSUE TITLE
[Feature Request] Add an optimized layout for mobile browsers. 

### ISSUE THREAD

**Issue by akoslaczko** [dunovank/jupyter-themes#109]
It would be great to have an option which enables an optimized layout for mobile browsers. Currently both code cells, and outputs are rendered incorrectly in portrait view (interestingly not in landscape view). Tried a bunch of browsers - on Android 7.1 with Termux - Chrome, Firefox, Dolphin, Naked Browser, and a few others, and all of them produces this problem.

Here are some screenshots:
![screenshot_20170406-182811](https://cloud.githubusercontent.com/assets/17934907/24765924/e53d16ec-1af9-11e7-94b7-8511016779c5.png)
![screenshot_20170406-182908](https://cloud.githubusercontent.com/assets/17934907/24765923/e53a81b6-1af9-11e7-9838-5502fe0b83e4.png)

**Comment by dunovank** [comment]
Interesting... any chance you'd be willing to submit a pull request? I'm a little pressed for time and don't have any mobile devices handy for testing. 

(I just released a new version that includes some minor changes to the input prompt style so you might try installing the new version on the off chance that it fixes this issue but I doubt it does)

**Comment by akoslaczko** [comment]
I've tried out the new version (0.15.3). Sadly, it did not resolve the issue (just as you've predicted):

![screenshot_20170407-015330](https://cloud.githubusercontent.com/assets/17934907/24780272/4b791d16-1b36-11e7-9fde-5939f7f4d957.png)

Sorry, but I won't be able to work on this project myself - at least not in the very near future (primary reason being that I've never worked with JS or Less before). However, I'd be happy to test any future versions on my device(s), if that's any help...

**Comment by dunovank** [comment]
Bummer... thanks for giving it a shot though. I'll see what I can do, will post any updates/test-requests here.

**Comment by akoslaczko** [comment]
Thanks in advance, will keep checking!
